[workspace]
channels = ["conda-forge"]
name = "gta5"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pixi-pycharm = ">=0.0.8,<0.0.9"
psutil = ">=7.0.0,<8"
pywin32 = ">=307,<308"
pygetwindow = ">=0.0.9,<0.0.10"
pytesseract = ">=0.3.13,<0.4"
numpy = ">=2.3.1,<3"
pyautogui = ">=0.9.54,<0.10"
pillow = ">=11.3.0,<12"
opencv = ">=4.11.0,<5"
pynput = ">=1.8.1,<2"
mss = ">=10.1.0,<11"
matplotlib = ">=3.9.1,<4"
pydirectinput = ">=1.0.4,<2"
